-- INSERT INTO posts(vendor_id, category, title, item_description, price, photo_url) VALUES (1, 'Sports Equipment', 'SHOES_FOR_SALE', 'big feet means big socks' , 1000, 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940');
-- INSERT INTO posts(vendor_id, category, title, item_description, price, photo_url) VALUES (2, 'Electronics', 'iPhone', 'call somebody' , 512, 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940');
-- INSERT INTO posts(vendor_id, category, title, item_description, price, photo_url) VALUES (3, 'PETS', 'Puppies', 'cute doggos' , 7146, 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940');
-- INSERT INTO posts(vendor_id, category, title, item_description, price, photo_url) VALUES (4, 'Hair Products', 'Shampoo', 'Hair goes Brrrr' , 714, 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940');
-- INSERT INTO posts(vendor_id, category, title, item_description, price, photo_url) VALUES (1, 'Musical Instruments', 'Guitar', 'strummers' , 10, 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940');
-- INSERT INTO posts(vendor_id, category, title, item_description, price, photo_url) VALUES (2, 'Books', 'Book', 'some description for the book' , 51235, 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940');
-- INSERT INTO posts(vendor_id, category, title, item_description, price, photo_url) VALUES (3, 'Automotive', 'Tesla', 'car goes brrrrrr' , 52315, 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940');
-- INSERT INTO posts(vendor_id, category, title, item_description, price, photo_url) VALUES (4, 'Electronics', 'Gaming PC', '500fps build' , 2327, 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940');

INSERT INTO posts(vendor_id, category, title, item_description, price, photo_url) VALUES (1, 'Sports Equipment', 'Golf-Club Set', '18-piece complete golf club package with Titanium driver' , 1200, 'https://m.media-amazon.com/images/I/81phSCzbHWL._AC_SX425_.jpg');
INSERT INTO posts(vendor_id, category, title, item_description, price, photo_url) VALUES (2, 'Electronics', 'iPhone', 'iPhone 15 Brand-New-in-Box. Bought because i had extra money. Never opened.' , 1850, 'https://www.gizbot.com/img/2017/10/appleiphonexretailboxrevealedbeforeofficialrelease-04-1507111734.jpg');
INSERT INTO posts(vendor_id, category, title, item_description, price, photo_url) VALUES (3, 'Pets', 'Slicker Brush', 'Slicker brush for all your pet grooming needs! Used once with my cat but he doesnt like it. Your pet might!' , 12, 'https://i5.walmartimages.com/asr/4ab25553-f45c-44f3-b1de-e2a8d36dcac0.c2af59fda671613b48e79ce44d33182a.jpeg');
INSERT INTO posts(vendor_id, category, title, item_description, price, photo_url) VALUES (4, 'Hair Products', 'Shampoo', 'GF gifted me this for my birthday. Dont know what to say. tried once so there is alot left.' , 10, 'https://media-cldnry.s-nbcnews.com/image/upload/newscms/2020_11/1547221/5d1fc336-23ef-4327-91ed-8c9d9700ca02-1-08685dd8e1e3081e4dc625304c1460e2-5e67e2052ec5f.jpeg');
INSERT INTO posts(vendor_id, category, title, item_description, price, photo_url) VALUES (1, 'Musical Instruments', 'Rare Guitar', 'The legendary Prince signed this back in 1997. Low asking price. Willing to let go at 6k' , 6000, 'https://multimedia.bbycastatic.ca/multimedia/products/500x500/152/15232/15232456.jpg');
INSERT INTO posts(vendor_id, category, title, item_description, price, photo_url) VALUES (2, 'Books', 'Harry-Potter Collection Set', 'A collection set for the Harry Potter series. Hard-cover and definitely no damage on the outside or inside.' , 200, 'https://dynamic.indigoimages.ca/v1/books/books/1408856786/1.jpg?quality=10&sale=6');
INSERT INTO posts(vendor_id, category, title, item_description, price, photo_url) VALUES (3, 'Automotive', 'Tesla', 'Tesla Roadster for sale. Dad gave it to me as a college gift. No use for it since I drive a Ford F150. Its just built different.' , 52315, 'https://www.tesla.com/sites/default/files/images/roadster/roadster-social.jpg');
INSERT INTO posts(vendor_id, category, title, item_description, price, photo_url) VALUES (4, 'Electronics', 'Gaming PC', 'Nvidia-GeForce RTX 3080 Ti. -- Intel. Core i9 10900K. -- Runs 1200 fps on REMASTERED setting on ANY GAME ' , 7200, 'https://images-ext-2.discordapp.net/external/3kMxllpVXGydHkLAWbD9r5Dz0BsQKwiLnkAjsz7d2lA/https/www.newegg.com/insider/wp-content/uploads/2019/02/Cougar_Build-3-1024x576.jpg');



