DROP TABLE IF EXISTS posts CASCADE;

CREATE TABLE posts (
  id SERIAL PRIMARY KEY NOT NULL,
  vendor_id INTEGER REFERENCES users(id) ON DELETE CASCADE,

  title VARCHAR(255) NOT NULL,
  item_description TEXT,
  price INTEGER NOT NULL DEFAULT 0,
  photo_url VARCHAR(255) NOT NULL,
  created_at TEXT,

  city VARCHAR(255) NOT NULL,

  active BOOLEAN NOT NULL DEFAULT TRUE
);
